In [1]:
import pandas as pd
from sqlalchemy import create_engine, text

engine = create_engine("postgresql+pg8000://user:secret@127.0.0.1:5432/lf8_lets_meet_db")

with engine.begin() as conn:
    print("verbunden mit:", conn.execute(text("SELECT current_database()")).scalar())

<jemalloc>: Unsupported system page size

verbunden mit: lf8_lets_meet_db

In [2]:
%load_ext sql
%config SqlMagic.displaycon = False
%sql postgresql+pg8000://user:secret@127.0.0.1:5432/lf8_lets_meet_db

Connecting to 'postgresql+pg8000://user:***@127.0.0.1:5432/lf8_lets_meet_db'

In [3]:
df = pd.read_excel("../Lets Meet DB Dump.xlsx")
df[["Nachname", "Vorname"]] = df["Nachname, Vorname"].str.split(", ", expand=True)
df = df.drop(columns = ["Nachname, Vorname"])

In [4]:
#df[["Straße Nr", "PLZ", "Ort"]] = df["Straße Nr, PLZ Ort"].str.split(", ", expand=True)
# funktioniert nicht....
# schauen wir was im Rest ist
split_cols = df["Straße Nr, PLZ Ort"].str.split(", ", expand=True)
df[["Straße Nr", "PLZ", "Ort", "Rest"]] = split_cols
len(df.dropna())
# 3 mal gibt es noch etwas zusätzliches
df["Rest"].dropna()
# 3 mal wird hinter der Stadt noch "Hansestadt" angegeben. Das kann sicher entfert werden
df = df.drop(columns = ["Rest", "Straße Nr, PLZ Ort"])

In [5]:
df.info()
df.head()
df["E-Mail"].value_counts()[df["E-Mail"].value_counts() > 1]
df["Interessiert an"].unique()
df["Geschlecht (m/w/nonbinary)"].unique()
mask = df["Telefon"].str.contains(r'0800', na=False)
print(df[mask]["Telefon"])
shortest_phone = df["Telefon"].str.len().idxmin()
print(df.loc[shortest_phone, "Telefon"])
df["Telefon"].value_counts()[df["Telefon"].value_counts() > 1]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1576 entries, 0 to 1575
Data columns (total 11 columns):
 #   Column                                                                           Non-Null Count  Dtype
---  ------                                                                           --------------  -----
 0   Telefon                                                                          1576 non-null   object
 1   Hobby1 %Prio1%; Hobby2 %Prio2%; Hobby3 %Prio3%; Hobby4 %Prio4%; Hobby5 %Prio5%;  1566 non-null   object
 2   E-Mail                                                                           1576 non-null   object
 3   Geschlecht (m/w/nonbinary)                                                       1576 non-null   object
 4   Interessiert an                                                                  1576 non-null   object
 5   Geburtsdatum                                                                     1576 non-null   object
 6   Nachname                                                                         1576 non-null   object
 7   Vorname                                                                          1576 non-null   object
 8   Straße Nr                                                                        1576 non-null   object
 9   PLZ                                                                              1576 non-null   object
 10  Ort                                                                              1576 non-null   object
dtypes: object(11)
memory usage: 135.6+ KB
Series([], Name: Telefon, dtype: object)
02372 8020

Series([], Name: count, dtype: int64)

In [6]:
df["Telefon"] = df["Telefon"].str.replace(r'[^0-9]', '', regex=True)
df["Telefon"]
shortest_phone = df["Telefon"].str.len().idxmin()
print(df.loc[shortest_phone, "Telefon"])

04774716

In [7]:
df["Geburtsdatum"] = pd.to_datetime(df["Geburtsdatum"], format="%d.%m.%Y").dt.normalize()
df["Geburtsdatum"]

0      1959-03-07
1      1958-02-28
2      1996-07-27
3      1992-12-09
4      1983-06-13
          ...
1571   1989-07-08
1572   1984-08-05
1573   1977-07-12
1574   1978-03-22
1575   1970-08-19
Name: Geburtsdatum, Length: 1576, dtype: datetime64[ns]

In [8]:
df["Prios"] = df["Hobby1 %Prio1%; Hobby2 %Prio2%; Hobby3 %Prio3%; Hobby4 %Prio4%; Hobby5 %Prio5%;"].str.replace(r'[^0-9;%]', '', regex=True)
split_prios = df["Prios"].str.split(";%", expand=True)
df[["Prio1", "Prio2", "Prio3", "Prio4", "Prio5"]] = split_prios
df["Prio1"] = df["Prio1"].str.replace(r'[^0-9]', '', regex=True)
df["Prio2"] = df["Prio2"].str.replace(r'[^0-9]', '', regex=True)
df["Prio3"] = df["Prio3"].str.replace(r'[^0-9]', '', regex=True)
df["Prio4"] = df["Prio4"].str.replace(r'[^0-9]', '', regex=True)
df["Prio5"] = df["Prio5"].str.replace(r'[^0-9]', '', regex=True)
df

,Telefon,Hobby1 %Prio1%; Hobby2 %Prio2%; Hobby3 %Prio3%; Hobby4 %Prio4%; Hobby5 %Prio5%;,E-Mail,Geschlecht (m/w/nonbinary),Interessiert an,Geburtsdatum,Nachname,Vorname,Straße Nr,PLZ,Ort,Prios,Prio1,Prio2,Prio3,Prio4,Prio5
0,023728020,Fremdsprachenkenntnisse erweitern %78%; Im Was...,martin.forster@web.ork,m,w,1959-03-07,Forster,Martin,Minslebener Str. 0,46286,Dorsten,%78%;%80%;%61%;%17%;,78,80,61,17,None
1,0622198689,Für jemanden kochen %57%; Mir die Probleme von...,tsanaklidou.elina@1mal1.te,w,m,1958-02-28,Elina,Tsanaklidou,Gartenweg 13,69126,Heidelberg,%57%;%21%;%53%;%25%;,57,21,53,25,None
2,0383422951,In der Stadt herumbummeln %94%; Mit Freunden z...,şahin.vildan@gmaiil.ork,w,m,1996-07-27,Vildan,şahin,Heinrich-Heine-Straße 99c,17489,Greifswald,%94%;%20%;%12%;%72%;,94,20,12,72,None
3,0162249788,An einer Gruppenreise teilnehmen %97%; Seine f...,ellen.bäumker@web.ork,w,m,1992-12-09,Bäumker,Ellen,Weidenring 39,81539,München,%97%;%91%;%93%;,97,91,93,None,None
4,0763167955,Ins Grüne fahren %23%; Holz hacken %67%; Fotos...,bekiroğlu.bahadır@autluuk.te,m,w,1983-06-13,Bahadır,Bekiroğlu,Eichendorffstraße 20,79379,Müllheim Baden,%23%;%67%;%84%;%69%;,23,67,84,69,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1571,0939187584,"Computerspiele spielen %6%; Stricken, Häkeln, ...",burkhard.wiesner@d-ohnline.ork,m,w,1989-07-08,Wiesner,Burkhard,Wilhelmstr. 58,88175,Scheidegg,%6%;%21%;,6,21,None,None,None
1572,0303957993,Seiner Familie etwas kaufen %46%; Über sein Ho...,klaus.hesselmann@ge-em-ix.te,m,w,1984-08-05,Hesselmann,Klaus,Barbyer Str. 79,10369,Berlin,%46%;%85%;%70%;%16%;,46,85,70,16,None
1573,041140577,"Ein Konzert, eine Opern- oder Ballettaufführun...",elisabeth.proll@autluuk.kom,w,m,1977-07-12,Proll,Elisabeth,Hauptstr. 96,30952,Ronnenberg,%25%;%36%;%26%;%67%;,25,36,26,67,None
1574,0819431701,Jemanden telefonisch zu einem Treffen einladen...,marieluise.wünnemann@gmaiil.ork,w,m,1978-03-22,Wünnemann,Marie Luise,Witts Allee 59 a,92360,Mühlhausen,%59%;%67%;%41%;%11%;,59,67,41,11,None
1575,0518188107,Zu einer Party gehen %35%; Jemandem behilflich...,frank.meyer@ge-em-ix.te,m,w,1970-08-19,Meyer,Frank,Friedensstr. 81,24568,Kaltenkirchen,%35%;%82%;%67%;%69%;,35,82,67,69,None

In [9]:
df["Hobbies"] = df["Hobby1 %Prio1%; Hobby2 %Prio2%; Hobby3 %Prio3%; Hobby4 %Prio4%; Hobby5 %Prio5%;"].str.replace(r'[%0-9]', '', regex=True)

split_hobbies = df["Hobbies"].str.split(" ; ", expand=True)
df[["Hobby1", "Hobby2", "Hobby3", "Hobby4", "Hobby5", "Hobby6"]] = split_hobbies


unique_hobbies = set()
for col in ['Hobby1', 'Hobby2', 'Hobby3', 'Hobby4', 'Hobby5', 'Hobby6']:
    unique_hobbies.update(df[col].dropna().unique())

print(len(unique_hobbies))

print(df["Hobby1"].nunique())

221
218

In [10]:
ls_unique_hobbies = list(unique_hobbies)
ls_unique_hobbies.remove('')
ls_unique_hobbies
df_unique_hobbies = pd.DataFrame(ls_unique_hobbies, columns=['beschreibung'])
df_unique_hobbies.reset_index(drop=True)
df_unique_hobbies.index += 1
df_unique_hobbies

                                        beschreibung
1                                     Gäste einladen
2                     Etwas planen oder organisieren
3                  Nur so herumsitzen und nachdenken
4                               Zu einer Party gehen
5                    Eine Sache klipp und klar sagen
..                                               ...
216  Sich über Philosophie oder Religion unterhalten
217                                           Reiten
218             Sich politisch oder sozial betätigen
219                    Jemandem eine Freude bereiten
220                              Für jemanden kochen

[220 rows x 1 columns]

In [11]:
df["Interessiert an nb"]=True
df["Interessiert an m"] = df["Interessiert an"].isin(["m", "mw"])
df["Interessiert an w"] = df["Interessiert an"].isin(["w", "mw"])

In [12]:
df[df["Interessiert an"] == "mw"]

,Telefon,Hobby1 %Prio1%; Hobby2 %Prio2%; Hobby3 %Prio3%; Hobby4 %Prio4%; Hobby5 %Prio5%;,E-Mail,Geschlecht (m/w/nonbinary),Interessiert an,Geburtsdatum,Nachname,Vorname,Straße Nr,PLZ,...,Hobbies,Hobby1,Hobby2,Hobby3,Hobby4,Hobby5,Hobby6,Interessiert an nb,Interessiert an m,Interessiert an w
9,0751787178,Etwas fertig stellen %95%; Blumen kaufen %48%;...,tatjana.stockbrink@iunitimail.kom,w,mw,1995-07-30,Stockbrink,Tatjana,Isolde-Kurz-Str. 126C,35394,...,Etwas fertig stellen ; Blumen kaufen ; Etwas l...,Etwas fertig stellen,Blumen kaufen,Etwas lernen und mich fortbilden,,None,None,True,True,True
81,0984073727,"Stricken, Häkeln, Sticken oder Nähen %14%; Etw...",insa.woelke@gmaiil.te,w,mw,1970-12-13,Woelke,Insa,Wasserstr. 45,81677,...,"Stricken, Häkeln, Sticken oder Nähen ; Etwas l...","Stricken, Häkeln, Sticken oder Nähen",Etwas lernen und mich fortbilden,,None,None,None,True,True,True
159,0544512746,Reiten %18%; Meine Arbeit geschickt ausführen ...,maria.peters@1mal1.te,w,mw,1988-06-30,Peters,Maria,Färbergasse 96,23812,...,Reiten ; Meine Arbeit geschickt ausführen ; Üb...,Reiten,Meine Arbeit geschickt ausführen,Über die Probleme anderer Leute nachdenken,Frische Luft schnappen,,None,True,True,True
165,0375157754,Skilaufen %35%; Im Wasser waten %60%; Sich ber...,christian.knobloch@d-ohnline.te,m,mw,1959-11-29,Knobloch,Christian,Am Gradeberg 83 c,7747,...,Skilaufen ; Im Wasser waten ; Sich beruflich e...,Skilaufen,Im Wasser waten,Sich beruflich engagieren,Blumen kaufen,"Romane, Erzählungen, Theaterstücke oder Gedich...",,True,True,True
176,0222725840,Sich um Zimmerpflanzen kümmern %10%; Ein Nicke...,irmgard.dube@gmaiil.kom,w,mw,1981-04-17,Dube,Irmgard,Philippstr. 79,53359,...,Sich um Zimmerpflanzen kümmern ; Ein Nickerche...,Sich um Zimmerpflanzen kümmern,Ein Nickerchen machen,,None,None,None,True,True,True
179,0160449153,"Ein Konzert, eine Opern- oder Ballettaufführun...",elisabeth.arens@a-o-l.te,w,mw,1991-02-21,Arens,Elisabeth,Hermann-Löns-Str. 84A,31241,...,"Ein Konzert, eine Opern- oder Ballettaufführun...","Ein Konzert, eine Opern- oder Ballettaufführun...",Mich laut beschweren,Musik hören,"Private Sachen erledigen, die schon lange lieg...",,None,True,True,True
187,0212776944,Auf mich zukommende Situationen in Gedanken be...,wernher.burnus@d-ohnline.te,m,mw,1967-06-07,Burnus,Wernher,Lerchenstieg 56-57,42699,...,Auf mich zukommende Situationen in Gedanken be...,Auf mich zukommende Situationen in Gedanken be...,,None,None,None,None,True,True,True
196,0568382639,"Sich im Freien aufhalten (im Park, Garten etc....",guido.pilz@d-ohnline.te,m,mw,1986-01-28,Pilz,Guido,Görlitzer Str 78,27729,...,"Sich im Freien aufhalten (im Park, Garten etc....","Sich im Freien aufhalten (im Park, Garten etc.)",Streit aus dem Wege gehen,Kreuzworträtsel lösen oder ein Puzzle legen,Positive Zukunftspläne schmieden,,None,True,True,True
221,0393159860,Verwandte besuchen %8%; Andere Leute betrachte...,karin.kösters@d-ohnline.te,w,mw,1984-05-08,Kösters,Karin,Breslauer-Str. 63,18437,...,Verwandte besuchen ; Andere Leute betrachten ;...,Verwandte besuchen,Andere Leute betrachten,Mich meinen Wunschträumen hingeben,,None,None,True,True,True
287,0507538915,Verwandte besuchen %6%; Gegenstände reparieren...,udo.lensker@ge-em-ix.ork,m,mw,1969-12-08,Lensker,Udo,Bürgermeister-Fuchs-Str. 79,20257,...,Verwandte besuchen ; Gegenstände reparieren ; ...,Verwandte besuchen,Gegenstände reparieren,Ausschlafen,,None,None,True,True,True
450,0338180602,Sich um neue Arbeit bewerben %15%; Antiquitäte...,horváth.tibor@autluuk.te,m,mw,1988-04-30,Tibor,Horváth,Mörikestraße 128,14776,...,Sich um neue Arbeit bewerben ; Antiquitäten re...,Sich um neue Arbeit bewerben,"Antiquitäten restaurieren, Möbel aufarbeiten",,None,None,None,True,True,True
483,0231473335,Mit Fremden ins Gespräch kommen %14%; Mit Beka...,stefan.essling@d-ohnline.te,m,mw,1970-11-29,Essling,Stefan,Liegnitzer Str. 48,44319,...,Mit Fremden ins Gespräch kommen ; Mit Bekannte...,Mit Fremden ins Gespräch kommen,Mit Bekannten telefonieren,,None,None,None,True,True,True
494,0241850556,Etwas verleihen %91%; Mit Freunden oder Bekann...,wénfū.mián@autluuk.te,w,mw,1979-11-23,Mián,Wénfū,Bachstraße 95,52066,...,Etwas verleihen ; Mit Freunden oder Bekannten ...,Etwas verleihen,Mit Freunden oder Bekannten zusammen essen,Seine finanziellen Angelegenheiten regeln,Für einen guten Zweck spenden,,None,True,True,True
584,0355692429,"Mit jemandem zusammen sein, den man mag %15%; ...",oliver.kanzog@d-ohnline.te,m,mw,1998-01-03,Kanzog,Oliver,Albrecht-Dürer-Str 125,4600,...,"Mit jemandem zusammen sein, den man mag ; Sich...","Mit jemandem zusammen sein, den man mag",Sich beruflich engagieren,"Stricken, Häkeln, Sticken oder Nähen",Ausschlafen,,None,True,True,True
609,0728936774,"Sich im Freien aufhalten (im Park, Garten etc....",holger.steinbach@d-ohnline.te,m,mw,1987-09-13,Steinbach,Holger,Untergath 105,74255,...,"Sich im Freien aufhalten (im Park, Garten etc....","Sich im Freien aufhalten (im Park, Garten etc.)",Für sich selbst Dinge einkaufen,Tagebuch schreiben,Für einen guten Zweck spenden,,None,True,True,True
623,033842242,Meine Arbeit geschickt ausführen %47%; Die Bib...,rosemarie.jethon@gmaiil.ork,w,mw,1973-12-29,Jethon,Rosemarie,Blumenweg 42 b,16928,...,Meine Arbeit geschickt ausführen ; Die Bibel o...,Meine Arbeit geschickt ausführen,Die Bibel oder andere religiöse Schriften lesen,,None,None,None,True,True,True
664,0160167203,Bowling spielen %4%; Computer-Netzwerk-Partys ...,hubert.appel@a-o-l.te,m,mw,1989-02-22,Appel,Hubert,Puttschen 73 c,56070,...,Bowling spielen ; Computer-Netzwerk-Partys ; F...,Bowling spielen,Computer-Netzwerk-Partys,Für andere sorgen,Zeitung lesen,Etwas lernen und mich fortbilden,,True,True,True
702,023333621,Eine Blume oder Pflanze sehen oder daran riech...,gerlind.feuerhahn@1mal1.kom,w,mw,1981-10-29,Feuerhahn,Gerlind,Rumfordstr. 107,58256,...,Eine Blume oder Pflanze sehen oder daran riech...,Eine Blume oder Pflanze sehen oder daran riechen,Etwas planen oder organisieren,,None,None,None,True,True,True
814,0415772770,In ein Lokal gehen %100%; Gemeinsam Probleme l...,christiane.richter@d-ohnline.te,w,mw,1971-08-03,Richter,Christiane,Haagstr. 93,29323,...,In ein Lokal gehen ; Gemeinsam Probleme lösen ...,In ein Lokal gehen,Gemeinsam Probleme lösen,Mit Bekannten telefonieren,,None,None,True,True,True
880,0302035418,Post lesen %83%; Ausschlafen %72%;,fritz.hengelbrock@d-ohnline.ork,m,mw,1984-03-22,Hengelbrock,Fritz,Am Meikenhof 118 c,13156,...,Post lesen ; Ausschlafen ;,Post lesen,Ausschlafen,,None,None,None,True,True,True
884,0201129596,Videos ansehen %84%; Eine Blume oder Pflanze s...,hedwig.berg@d-ohnline.te,w,mw,1982-08-02,Berg,Hedwig,Luruper Hauptstr. 105,45128,...,Videos ansehen ; Eine Blume oder Pflanze sehen...,Videos ansehen,Eine Blume oder Pflanze sehen oder daran riechen,Mit Bekannten telefonieren,,None,None,True,True,True
918,0540246008,An einem Treffen oder einer Feier der Familie ...,paolamaria.olschowka@web.ork,w,mw,1995-01-26,Olschowka,Paola Maria,Engerstr. 32 c,23566,...,An einem Treffen oder einer Feier der Familie ...,An einem Treffen oder einer Feier der Familie ...,Einfach mit guten Freunden zwanglos plaudern,Über die Probleme anderer Leute nachdenken,"Private Sachen erledigen, die schon lange lieg...",,None,True,True,True
1031,0622343238,Freunde besuchen %45%; Mit Freunden zusammen s...,eckhard.wagner@autluuk.te,m,mw,1979-05-16,Wagner,Eckhard,Voigtwiese 129,76534,...,Freunde besuchen ; Mit Freunden zusammen sein ;,Freunde besuchen,Mit Freunden zusammen sein,,None,None,None,True,True,True
1048,0416241569,Sich beruflich engagieren %89%; Etwas schmackh...,bernd.roelfs@iunitimail.te,m,mw,1985-01-20,Roelfs,Bernd,Hermannstr. 14,31246,...,Sich beruflich engagieren ; Etwas schmackhafte...,Sich beruflich engagieren,Etwas schmackhaftes zu mir nehmen,"Private Sachen erledigen, die schon lange lieg...",,None,None,True,True,True
1100,0607228132,Tanzen %67%; Fernsehen %56%; Für einen guten Z...,matthias.vandülmen@web.te,m,mw,1959-11-09,van Dülmen,Matthias,Thörener Str. 103,71720,...,Tanzen ; Fernsehen ; Für einen guten Zweck spe...,Tanzen,Fernsehen,Für einen guten Zweck spenden,,None,None,True,True,True
1112,0205351643,In einem Chor singen %89%; Positive Zukunftspl...,antonioj..böhnke@d-ohnline.kom,m,mw,2001-11-12,Böhnke,Antonio J.,Max-Koska-Str. 57A,45964,...,In einem Chor singen ; Positive Zukunftspläne ...,In einem Chor singen,Positive Zukunftspläne schmieden,,None,None,None,True,True,True
1153,020956813,Jemanden telefonisch zu einem Treffen einladen...,josef.bratz@d-ohnline.ork,m,mw,1996-04-06,Bratz,Josef,Mettmanner Str. 4,46147,...,Jemanden telefonisch zu einem Treffen einladen...,Jemanden telefonisch zu einem Treffen einladen,Radio hören,Die Sterne oder den Mond beobachten,,None,None,True,True,True
1173,0853392732,Zu einer Sportveranstaltung gehen %55%; chille...,edzard.zeuch@gmaiil.te,m,mw,2001-05-13,Zeuch,Edzard,Wolfenbütteler Str. 8,92507,...,Zu einer Sportveranstaltung gehen ; chillen ; ...,Zu einer Sportveranstaltung gehen,chillen,Barfuß laufen,"Antiquitäten restaurieren, Möbel aufarbeiten",,None,True,True,True
1271,025133581,"Mit jemandem zusammen sein, den man mag %86%; ...",ursula.gehlen@web.ork,w,mw,1960-03-29,Gehlen,Ursula,Papendamm 88A,52062,...,"Mit jemandem zusammen sein, den man mag ; Comp...","Mit jemandem zusammen sein, den man mag",Computerspiele spielen,Einfach alleine sein,Auf mich zukommende Situationen in Gedanken be...,,None,True,True,True
1412,0521216095,Einen Vergnügungspark besuchen %88%; Computers...,christiane.morsch@ge-em-ix.te,w,mw,1962-04-17,Morsch,Christiane,Grimsehlstr. 3,28197,...,Einen Vergnügungspark besuchen ; Computerspiel...,Einen Vergnügungspark besuchen,Computerspiele spielen,"Private Sachen erledigen, die schon lange lieg...",,None,None,True,True,True
1455,0509532608,Aufräumen und putzen %94%;,martha.lorenz@d-ohnline.kom,w,mw,1985-08-24,Lorenz,Martha,Diakonissenstr. 50A,21509,...,Aufräumen und putzen ;,Aufräumen und putzen,,None,None,None,None,True,True,True
1538,0235906087,Mit meiner Meinung Recht haben %32%; Abends se...,ralf.fischer@autluuk.kom,m,mw,1959-09-02,Fischer,Ralf,Lion-Feuchtwanger-Str. 78,44879,...,Mit meiner Meinung Recht haben ; Abends seinem...,Mit meiner Meinung Recht haben,Abends seinem Partner Ereignisse des Tages erz...,Nur so herumsitzen und nachdenken,,None,None,True,True,True
1570,0886129063,Kräuter/Pilze sammeln %57%; Zeitschriften durc...,polishchuk.eduard@d-ohnline.ork,m,mw,1971-09-16,Eduard,Polishchuk,Weinbergstraße 75,86956,...,Kräuter/Pilze sammeln ; Zeitschriften durchblä...,Kräuter/Pilze sammeln,Zeitschriften durchblättern/lesen,Die Bibel oder andere religiöse Schriften lesen,,None,None,True,True,True

In [13]:
df.dtypes

Telefon                                                                                    object
Hobby1 %Prio1%; Hobby2 %Prio2%; Hobby3 %Prio3%; Hobby4 %Prio4%; Hobby5 %Prio5%;            object
E-Mail                                                                                     object
Geschlecht (m/w/nonbinary)                                                                 object
Interessiert an                                                                            object
Geburtsdatum                                                                       datetime64[ns]
Nachname                                                                                   object
Vorname                                                                                    object
Straße Nr                                                                                  object
PLZ                                                                                        object
Ort                                                                                        object
Prios                                                                                      object
Prio1                                                                                      object
Prio2                                                                                      object
Prio3                                                                                      object
Prio4                                                                                      object
Prio5                                                                                      object
Hobbies                                                                                    object
Hobby1                                                                                     object
Hobby2                                                                                     object
Hobby3                                                                                     object
Hobby4                                                                                     object
Hobby5                                                                                     object
Hobby6                                                                                     object
Interessiert an nb                                                                           bool
Interessiert an m                                                                            bool
Interessiert an w                                                                            bool
dtype: object

In [14]:
shortest_hobby = df["Hobby1 %Prio1%; Hobby2 %Prio2%; Hobby3 %Prio3%; Hobby4 %Prio4%; Hobby5 %Prio5%;"].str.len().idxmin()
print(df.loc[shortest_hobby, "Hobby1 %Prio1%; Hobby2 %Prio2%; Hobby3 %Prio3%; Hobby4 %Prio4%; Hobby5 %Prio5%;"])

Beten %34%;

In [15]:
df.reset_index(drop=True)
df.index +=1

In [16]:
DDL_KUNDE = """
CREATE TABLE kunde (
    kunde_id int PRIMARY KEY,
    name text NOT NULL,
    vorname text NOT NULL,
    email text NOT NULL UNIQUE,
    telefon text,
    geschlecht text NOT NULL,
    geburtsdatum date NOT NULL
)
"""

DDL_INTERESSE ="""
CREATE TABLE interesse (
    interesse_id serial PRIMARY KEY,
    kunde_id integer REFERENCES kunde (kunde_id),
    maennlich boolean NOT NULL,
    weiblich boolean NOT NULL,
    nonbinary boolean NOT NULL    
)
"""

DDL_ADRESSE="""
CREATE TABLE adresse (
    adresse_id serial PRIMARY KEY,
    kunde_id integer REFERENCES kunde (kunde_id),
    strasse_nummer text NOT NULL,
    plz text NOT NULL,
    ort text NOT NULL
)
"""

DLL_HOBBY="""
CREATE TABLE hobby (
    hobby_id int PRIMARY KEY,
    beschreibung text NOT NULL
)
"""

DLL_HOBBY_KUNDE="""
CREATE TABLE hobby_kunde (
    kunde_id integer REFERENCES kunde (kunde_id),
    hobby_id integer REFERENCES hobby (hobby_id),
    prio integer NOT NULL,
    CONSTRAINT pk_hobby_kunde PRIMARY KEY (kunde_id, hobby_id)
)
"""


with engine.begin() as conn:
    conn.execute(text("DROP TABLE IF EXISTS hobby_kunde"))
    conn.execute(text("DROP TABLE IF EXISTS interesse"))
    conn.execute(text("DROP TABLE IF EXISTS adresse"))
    conn.execute(text("DROP TABLE IF EXISTS hobby"))
    conn.execute(text("DROP TABLE IF EXISTS kunde"))
    conn.execute(text(DDL_KUNDE))
    conn.execute(text(DLL_HOBBY))
    conn.execute(text(DDL_ADRESSE))
    conn.execute(text(DDL_INTERESSE))
    conn.execute(text(DLL_HOBBY_KUNDE))

print("Tabellen angelegt")

Tabellen angelegt

In [17]:
# Kunde-Tabelle

kunde_data = df[["Nachname", "Vorname", "E-Mail", "Telefon", "Geschlecht (m/w/nonbinary)", "Geburtsdatum"]].copy()
kunde_data.columns = ["name", "vorname", "email", "telefon", "geschlecht", "geburtsdatum"]
kunde_data.to_sql("kunde", engine, if_exists="append", index=True, index_label="kunde_id")

1576

In [18]:
%%sql
SELECT * from KUNDE

1576 rows affected.

+----------+------------+-------------+-----------------------------------+------------+------------+--------------+
| kunde_id |    name    |   vorname   |               email               |  telefon   | geschlecht | geburtsdatum |
+----------+------------+-------------+-----------------------------------+------------+------------+--------------+
|    1     |  Forster   |    Martin   |       martin.forster@web.ork      | 023728020  |     m      |  1959-03-07  |
|    2     |   Elina    | Tsanaklidou |     tsanaklidou.elina@1mal1.te    | 0622198689 |     w      |  1958-02-28  |
|    3     |   Vildan   |    şahin    |      şahin.vildan@gmaiil.ork      | 0383422951 |     w      |  1996-07-27  |
|    4     |  Bäumker   |    Ellen    |       ellen.bäumker@web.ork       | 0162249788 |     w      |  1992-12-09  |
|    5     |  Bahadır   |  Bekiroğlu  |    bekiroğlu.bahadır@autluuk.te   | 0763167955 |     m      |  1983-06-13  |
|    6     |    Fink    |  Karl-Heinz |    karl-heinz.fink@ge-em-ix.kom   | 0235530742 |     m      |  1980-08-07  |
|    7     |   Gövert   |     Dirk    |      dirk.gövert@autluuk.ork      | 0271300135 |     m      |  1983-04-18  |
|    8     |   Rüsing   |     Paul    |       paul.rüsing@1mal1.kom       | 0425196481 |     m      |  1967-01-19  |
|    9     | Wiesnewski |     Tim     |    tim.wiesnewski@d-ohnline.te    | 0939218291 |     m      |  1968-02-21  |
|    10    | Stockbrink |   Tatjana   | tatjana.stockbrink@iunitimail.kom | 0751787178 |     w      |  1995-07-30  |
+----------+------------+-------------+-----------------------------------+------------+------------+--------------+
Truncated to displaylimit of 10.

In [19]:
# Adresse-Tabelle
adresse_data = df[["Straße Nr", "PLZ", "Ort"]].copy()
adresse_data.columns = ["strasse_nummer", "plz", "ort"]
adresse_data.to_sql("adresse", engine, if_exists="append", index=True, index_label="kunde_id")

1576

In [20]:
%%sql
SELECT * from adresse

1576 rows affected.

+------------+----------+---------------------------+-------+----------------+
| adresse_id | kunde_id |       strasse_nummer      |  plz  |      ort       |
+------------+----------+---------------------------+-------+----------------+
|     1      |    1     |     Minslebener Str. 0    | 46286 |    Dorsten     |
|     2      |    2     |        Gartenweg 13       | 69126 |   Heidelberg   |
|     3      |    3     | Heinrich-Heine-Straße 99c | 17489 |   Greifswald   |
|     4      |    4     |       Weidenring 39       | 81539 |    München     |
|     5      |    5     |    Eichendorffstraße 20   | 79379 | Müllheim Baden |
|     6      |    6     |        Lindenweg 80       | 44795 |     Bochum     |
|     7      |    7     |     Rahlenbeckstr. 100    | 56070 |    Koblenz     |
|     8      |    8     |       Im Brückle 44       | 33334 |   Gütersloh    |
|     9      |    9     |       Wilhelmsaue 29      | 88131 |     Lindau     |
|     10     |    10    |   Isolde-Kurz-Str. 126C   | 35394 |     Gießen     |
+------------+----------+---------------------------+-------+----------------+
Truncated to displaylimit of 10.

In [21]:
# intresse Tabbel
interesse_data = df[["Interessiert an nb", "Interessiert an m", "Interessiert an w"]].copy()
interesse_data.columns = ["nonbinary", "maennlich", "weiblich"]
interesse_data.to_sql("interesse", engine, if_exists="append", index=True, index_label="kunde_id")

1576

In [22]:
%%sql
select * from interesse

1576 rows affected.

+--------------+----------+-----------+----------+-----------+
| interesse_id | kunde_id | maennlich | weiblich | nonbinary |
+--------------+----------+-----------+----------+-----------+
|      1       |    1     |   False   |   True   |    True   |
|      2       |    2     |    True   |  False   |    True   |
|      3       |    3     |    True   |  False   |    True   |
|      4       |    4     |    True   |  False   |    True   |
|      5       |    5     |   False   |   True   |    True   |
|      6       |    6     |   False   |   True   |    True   |
|      7       |    7     |   False   |   True   |    True   |
|      8       |    8     |   False   |   True   |    True   |
|      9       |    9     |   False   |   True   |    True   |
|      10      |    10    |    True   |   True   |    True   |
+--------------+----------+-----------+----------+-----------+
Truncated to displaylimit of 10.

In [23]:
df_unique_hobbies.to_sql("hobby", engine, if_exists="append", index=True, index_label="hobby_id")

220

In [24]:
%%sql
select * from hobby

220 rows affected.

+----------+--------------------------------------------------------+
| hobby_id |                      beschreibung                      |
+----------+--------------------------------------------------------+
|    1     |                     Gäste einladen                     |
|    2     |             Etwas planen oder organisieren             |
|    3     |           Nur so herumsitzen und nachdenken            |
|    4     |                  Zu einer Party gehen                  |
|    5     |            Eine Sache klipp und klar sagen             |
|    6     | Den Himmel, Wolken oder einen breiten Sturm beobachten |
|    7     |  Lebensmittel einmachen, einfrieren, Vorräte anlegen   |
|    8     |                       Radfahren                        |
|    9     |             Sich um Zimmerpflanzen kümmern             |
|    10    |                   Mich schön kleiden                   |
+----------+--------------------------------------------------------+
Truncated to displaylimit of 10.

In [25]:
hobby_kunde_data = pd.DataFrame(columns=["kunde_id", "hobby_id", "prio"])